---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default
spec:
  sourceRepos:
  - 'https://github.com/nu12/argocd.git'
  destinations:
  - namespace: 'argocd'
    server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra
spec:
  sourceRepos:
  - 'https://github.com/nu12/argocd.git'
  - 'https://github.com/kubernetes-sigs/gateway-api.git'
  - 'https://github.com/traefik/traefik.git'
  - 'https://github.com/rabbitmq/cluster-operator.git'
  - 'https://traefik.github.io/charts'
  destinations:
  - namespace: '*'
    server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: apps
spec:
  sourceRepos:
  - 'https://github.com/nu12/fakturo.git'
  - 'https://github.com/nu12/argocd.git'
  destinations:
  - namespace: 'fakturo'
    server: 'https://kubernetes.default.svc'
  - namespace: 'fizzy'
    server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dev
spec:
  sourceRepos:
  - 'https://github.com/nu12/argocd.git'
  destinations:
  - namespace: 'mailpit'
    server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  namespaceResourceWhitelist:
  - group: ''
    kind: ConfigMap
  - group: ''
    kind: Secret
  - group: ''
    kind: Service
  - group: 'apps'
    kind: Deployment
  