---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default
spec:
  sourceRepos:
  - 'https://github.com/nu12/argocd.git'
  destinations:
  - namespace: 'argocd'
    server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra
spec:
  sourceRepos:
  - 'https://github.com/kubernetes-sigs/gateway-api.git'
  - 'https://github.com/traefik/traefik.git'
  - 'https://github.com/rabbitmq/cluster-operator.git'
  - 'https://traefik.github.io/charts'
  destinations:
  - namespace: '*'
    server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: fakturo
spec:
  sourceRepos:
  - 'https://github.com/nu12/fakturo.git'
  - 'https://github.com/nu12/argocd.git'
  destinations:
  - namespace: 'fakturo'
    server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'