apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fakturo
spec:
  destination:
    namespace: fakturo
    server: https://kubernetes.default.svc
  source:
    path: 'helm'
    repoURL: https://github.com/nu12/fakturo.git
    targetRevision: main
    helm:
      values: |
        jobs:
          enabled: false
        gateway:
          enabled: true
          gatewayClassName: traefik
          listeners:
          - allowedRoutes:
              namespaces:
                from: Same
            name: websecure
            port: 8443
            protocol: HTTPS
            tls:
              mode: Terminate
              certificateRefs:
                - group: ''
                  kind: Secret
                  name: fakturo-tls
        httpRoute:
          enabled: true
          hostnames:
          - fakturo.pi
          parentRefs:
          - name: fakturo
            sectionName: websecure
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true