---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-operator
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  sources:
  - path: config/installation
    repoURL: https://github.com/rabbitmq/cluster-operator.git
    targetRevision: v2.18.0
  project: infra